\c live024

ALTER TABLE orders ADD FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE;
-- RESTRICT / NO ACTION
-- CASCADE
-- SET NULL (NAO PODE TEM CONSTRAIN NOT NULL)
-- SET DEFAULT
